export const mockEducators = {
  applying: [
    {
      id: 1,
      name: "Alice Johnson",
      pfp: "/Default_pfp.jpg",
      role: "educator",
      nickname: "AJ",
      age: 29,
      birthday: "1996-03-15",
      gender: "Female",
      email: "alice@example.com",
      phone: "123-456-7890",
      qualifications: "M.Ed in Mathematics",
      resume: "resume-alice.pdf",
    },
    {
      id: 2,
      name: "Mark Thompson",
      pfp: "/Default_pfp.jpg",
      role: "mentor",
      nickname: "MarkT",
      age: 41,
      birthday: "1984-06-22",
      gender: "Male",
      email: "markt@example.com",
      phone: "555-321-9876",
      qualifications: "MBA, Certified Career Coach",
      resume: "resume-mark.pdf",
    },
    {
      id: 3,
      name: "Sophia Ramirez",
      pfp: "/Default_pfp.jpg",
      role: "counselor",
      nickname: "Sophie",
      age: 33,
      birthday: "1992-01-09",
      gender: "Female",
      email: "sramirez@example.com",
      phone: "444-567-8888",
      qualifications: "M.A. in Counseling Psychology",
      resume: "resume-sophia.pdf",
    },
    {
      id: 4,
      name: "Daniel Wu",
      pfp: "/Default_pfp.jpg",
      role: "trainer",
      nickname: "Dan",
      age: 38,
      birthday: "1987-12-01",
      gender: "Male",
      email: "danwu@example.com",
      phone: "222-999-3333",
      qualifications: "Certified Corporate Trainer, PMP",
      resume: "resume-daniel.pdf",
    },
    {
      id: 5,
      name: "Hannah Kim",
      pfp: "/Default_pfp.jpg",
      role: "conversationalist",
      nickname: "HK",
      age: 26,
      birthday: "1999-07-18",
      gender: "Female",
      email: "hannahkim@example.com",
      phone: "777-111-4444",
      qualifications: "B.A. in Linguistics, ESL Specialist",
      resume: "resume-hannah.pdf",
    },
  ],

  registered: [
    {
      id: 6,
      name: "David Lee",
      pfp: "/Default_pfp.jpg",
      role: "mentor",
      nickname: "Dave",
      age: 35,
      birthday: "1990-08-10",
      gender: "Male",
      email: "david@example.com",
      phone: "987-654-3210",
      qualifications: "PhD in Physics",
      resume: "resume-david.pdf",
      schedule: ["Mon 9AM - 10AM", "Wed 2PM - 3PM", "Fri 1PM - 2PM"],
    },
    {
      id: 7,
      name: "Priya Patel",
      pfp: "/Default_pfp.jpg",
      role: "educator",
      nickname: "P",
      age: 30,
      birthday: "1995-02-11",
      gender: "Female",
      email: "priya@example.com",
      phone: "321-555-6789",
      qualifications: "M.Ed in Special Education",
      resume: "resume-priya.pdf",
      schedule: ["Tue 10AM - 11AM", "Thu 4PM - 5PM"],
    },
    {
      id: 8,
      name: "James Carter",
      pfp: "/Default_pfp.jpg",
      role: "counselor",
      nickname: "JC",
      age: 45,
      birthday: "1980-11-03",
      gender: "Male",
      email: "jcarter@example.com",
      phone: "666-444-2222",
      qualifications: "Licensed School Counselor (M.A.)",
      resume: "resume-james.pdf",
      schedule: ["Mon 3PM - 4PM", "Thu 9AM - 10AM"],
    },
    {
      id: 9,
      name: "Linda Green",
      pfp: "/Default_pfp.jpg",
      role: "trainer",
      nickname: "LG",
      age: 37,
      birthday: "1988-05-21",
      gender: "Female",
      email: "lgreen@example.com",
      phone: "111-888-5555",
      qualifications: "Certified Personal Development Coach",
      resume: "resume-linda.pdf",
      schedule: ["Wed 1PM - 2PM", "Fri 11AM - 12PM"],
    },
    {
      id: 10,
      name: "Omar Hassan",
      pfp: "/Default_pfp.jpg",
      role: "conversationalist",
      nickname: "O",
      age: 28,
      birthday: "1997-09-30",
      gender: "Male",
      email: "omar@example.com",
      phone: "999-777-1234",
      qualifications: "TESOL Certified, Multilingual",
      resume: "resume-omar.pdf",
      schedule: ["Tue 6PM - 7PM", "Sat 10AM - 11AM"],
    },
    {
      id: 11,
      name: "Rachel Cohen",
      pfp: "/Default_pfp.jpg",
      role: "mentor",
      nickname: "Rach",
      age: 32,
      birthday: "1993-04-14",
      gender: "Female",
      email: "rachelc@example.com",
      phone: "123-888-4567",
      qualifications: "M.S. in Data Science, Career Mentor",
      resume: "resume-rachel.pdf",
      schedule: ["Mon 5PM - 6PM", "Thu 2PM - 3PM"],
    },
    {
      id: 12,
      name: "Ethan Brown",
      pfp: "/Default_pfp.jpg",
      role: "educator",
      nickname: "EB",
      age: 40,
      birthday: "1985-02-20",
      gender: "Male",
      email: "ethanb@example.com",
      phone: "321-123-4567",
      qualifications: "M.Ed in English Literature",
      resume: "resume-ethan.pdf",
      schedule: ["Wed 9AM - 10AM", "Fri 3PM - 4PM"],
    },
    {
      id: 13,
      name: "Mia Lopez",
      pfp: "/Default_pfp.jpg",
      role: "counselor",
      nickname: "Mimi",
      age: 34,
      birthday: "1991-06-25",
      gender: "Female",
      email: "mia@example.com",
      phone: "444-222-6666",
      qualifications: "M.S. in Educational Psychology",
      resume: "resume-mia.pdf",
      schedule: ["Tue 1PM - 2PM", "Thu 11AM - 12PM"],
    },
    {
      id: 14,
      name: "Tom Nguyen",
      pfp: "/Default_pfp.jpg",
      role: "trainer",
      nickname: "Tommy",
      age: 36,
      birthday: "1989-08-12",
      gender: "Male",
      email: "tomn@example.com",
      phone: "555-777-9999",
      qualifications: "Corporate Leadership Trainer",
      resume: "resume-tom.pdf",
      schedule: ["Mon 11AM - 12PM", "Fri 4PM - 5PM"],
    },
    {
      id: 15,
      name: "Grace Miller",
      pfp: "/Default_pfp.jpg",
      role: "conversationalist",
      nickname: "GM",
      age: 27,
      birthday: "1998-12-19",
      gender: "Female",
      email: "gracem@example.com",
      phone: "222-444-1111",
      qualifications: "Language Coach, Polyglot (5 languages)",
      resume: "resume-grace.pdf",
      schedule: ["Sat 2PM - 3PM", "Sun 11AM - 12PM"],
    },
  ],
};
